---
- hosts: 127.0.0.1
  name: 07 - Create NSX Transport Zones
  gather_facts: false
  vars_files: 
    - ../../answerfile.yml

  tasks:
    - name: Create NSX Transport Zones
      vmware.ansible_for_nsxt.nsxt_transport_zones:
        hostname: "{{ nsx_hostname }}.{{ nsx_domain }}"
        username: "{{ nsx_admin_user }}"
        password: "{{ nsx_admin_password }}"
        validate_certs: "{{ nsx_validate_certs }}"
        resource_type: "TransportZone"
        display_name: "{{ item.display_name }}"
        description: "{{ item.description }}"
        #host_switch_mode is required for PRE 3.2 (Will error without)- It must NOT be set for 3.2+ (Will error if set - 'Json de-serialization error: property host_switch_mode is unrecognized.')
        host_switch_mode: "STANDARD" # PRE 3.2
        transport_type: "{{ item.transport_type }}"
        state: "{{ state }}"
      with_items: 
        - "{{ transportzones }}"
...